"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: todo
    version: 1.1.0

    Do not edit the class manually.
"""  # noqa: E501

from clients.http.todo.apis.todos_api import TodosApi

__all__ = [
    "TodosApi",
]
