"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: {{ service_name|to_snake_case }}
    version: {{ version }}

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

from typing import Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class Todo(BaseModel):
    id: int = Field(..., title="Id")
    title: str = Field(..., title="Title")
    description: Optional[str] = Field(None, title="Description")
    completed: Optional[bool] = Field(False, title="Completed")


class TodoCreate(BaseModel):
    title: str = Field(..., title="Title")
    description: Optional[str] = Field(None, title="Description")


class GetTodosTodosGetResponse200(RootModel[List[Todo]]):
    root: List[Todo] = Field(..., title="Response Get Todos Todos  Get")


class DeleteTodoTodosTodoIdDeleteResponse200(RootModel[Optional[Dict[str, str]]]):
    root: Optional[Dict[str, str]] = None


class ValidationErrorLocItem(RootModel[Union[str, int]]):
    root: Union[str, int]


class ValidationError(BaseModel):
    loc: List[ValidationErrorLocItem] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title="Detail")
