# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: todo
    version: 1.1.0

    Do not edit the class manually.
"""  # noqa: E501

from typing import Any
from httpx import Response

from restcodegen.restclient import Client


from clients.http.todo.models.api_models import (
    Todo,
    GetTodosTodosGetResponse200,
    DeleteTodoTodosTodoIdDeleteResponse200,
    TodoCreate,
)


class TodosApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def get_todos(
        self,
        **kwargs: Any,
    ) -> GetTodosTodosGetResponse200:
        """
        Get Todos.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            GetTodosTodosGetResponse200: ...
        """  # noqa: D205,E501

        response = self.get_todos_with_http_info(
            **kwargs,
        )
        return GetTodosTodosGetResponse200.model_validate_json(response.text)

    def get_todos_with_http_info(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        Get Todos.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url="/todos/",
            headers=headers,
            **kwargs,
        )
        return response

    def post_todos(
        self,
        todo_create: TodoCreate,  # noqa: E501
        **kwargs: Any,
    ) -> Todo:
        """
        Create Todo.

        Args:
            todo_create(TodoCreate): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Todo: ...
        """  # noqa: D205,E501

        response = self.post_todos_with_http_info(
            todo_create=todo_create,  # noqa: E501
            **kwargs,
        )
        return Todo.model_validate_json(response.text)

    def post_todos_with_http_info(
        self,
        todo_create: TodoCreate,  # noqa: E501
        **kwargs: Any,
    ) -> Response:
        """
        Create Todo.

        Args:
            todo_create(TodoCreate): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = todo_create.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})

        response = self.api_client.post(
            url="/todos/",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def delete_todos(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        Delete all todos.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            None: ...
        """  # noqa: D205,E501

        response = self.delete_todos_with_http_info(
            **kwargs,
        )
        return response

    def delete_todos_with_http_info(
        self,
        **kwargs: Any,
    ) -> Response:
        """
        Delete all todos.

        Args:
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.delete(
            url="/todos/",
            headers=headers,
            **kwargs,
        )
        return response

    def get_todos_todo_id(
        self,
        todo_id: int,
        **kwargs: Any,
    ) -> Todo:
        """
        Get Todo.

        Args:
            todo_id(int, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Todo: ...
        """  # noqa: D205,E501

        response = self.get_todos_todo_id_with_http_info(
            todo_id=todo_id,
            **kwargs,
        )
        return Todo.model_validate_json(response.text)

    def get_todos_todo_id_with_http_info(
        self,
        todo_id: int,
        **kwargs: Any,
    ) -> Response:
        """
        Get Todo.

        Args:
            todo_id(int, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.get(
            url=f"/todos/{todo_id}",
            headers=headers,
            **kwargs,
        )
        return response

    def put_todos_todo_id(
        self,
        todo_create: TodoCreate,  # noqa: E501
        todo_id: int,
        **kwargs: Any,
    ) -> Todo:
        """
        Update Todo.

        Args:
            todo_create(TodoCreate): ...
            todo_id(int, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Todo: ...
        """  # noqa: D205,E501

        response = self.put_todos_todo_id_with_http_info(
            todo_id=todo_id,
            todo_create=todo_create,  # noqa: E501
            **kwargs,
        )
        return Todo.model_validate_json(response.text)

    def put_todos_todo_id_with_http_info(
        self,
        todo_create: TodoCreate,  # noqa: E501
        todo_id: int,
        **kwargs: Any,
    ) -> Response:
        """
        Update Todo.

        Args:
            todo_create(TodoCreate): ...
            todo_id(int, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        content = todo_create.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})

        response = self.api_client.put(
            url=f"/todos/{todo_id}",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def delete_todos_todo_id(
        self,
        todo_id: int,
        **kwargs: Any,
    ) -> DeleteTodoTodosTodoIdDeleteResponse200:
        """
        Delete Todo.

        Args:
            todo_id(int, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            DeleteTodoTodosTodoIdDeleteResponse200: ...
        """  # noqa: D205,E501

        response = self.delete_todos_todo_id_with_http_info(
            todo_id=todo_id,
            **kwargs,
        )
        return DeleteTodoTodosTodoIdDeleteResponse200.model_validate_json(response.text)

    def delete_todos_todo_id_with_http_info(
        self,
        todo_id: int,
        **kwargs: Any,
    ) -> Response:
        """
        Delete Todo.

        Args:
            todo_id(int, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.delete(
            url=f"/todos/{todo_id}",
            headers=headers,
            **kwargs,
        )
        return response

    def patch_todos_todo_id_complete(
        self,
        todo_id: int,
        **kwargs: Any,
    ) -> Todo:
        """
        Complete Todo.

        Args:
            todo_id(int, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Todo: ...
        """  # noqa: D205,E501

        response = self.patch_todos_todo_id_complete_with_http_info(
            todo_id=todo_id,
            **kwargs,
        )
        return Todo.model_validate_json(response.text)

    def patch_todos_todo_id_complete_with_http_info(
        self,
        todo_id: int,
        **kwargs: Any,
    ) -> Response:
        """
        Complete Todo.

        Args:
            todo_id(int, required): ...
            **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

        Returns:
            Response: ...
        """  # noqa: D205,E501
        headers = kwargs.pop("headers", {})

        response = self.api_client.patch(
            url=f"/todos/{todo_id}/complete",
            headers=headers,
            **kwargs,
        )
        return response
